services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
  authserver:
    build: ./authserver
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://testuser:password@mongodb:27017/authdb
    ports:
      - 4000:4000
    links:
      - mongodb:database
